**Todas las funciones deben estar comentadas y deben tener validaciones de acuerdo a los parametros que reciban**

**Todas las funciones deben funcionar para cualquier input proporcionado que cumpla las especificaciones, no solo para el ejemplo dado**

1) Escriba una función usando NumPy para crear una matriz de registros a partir de una matriz regular dada

- input

In [ ]:
array

array([['Rodrigo Gonzalez', '$234,345', 'Grupo B'],
       ['Rodrigo Gonzalez 2', '$234,345.12', 'Grupo C'],
       ['Rodrigo Gonzalez 3', '$2,345', 'Grupo D']], dtype='<U18')

- Output

In [ ]:
result

rec.array([(b'Rodrigo Gonzalez', b'$234,345', b'Grupo B'),
           (b'Rodrigo Gonzalez 2', b'$234,345.12', b'Grupo C'),
           (b'Rodrigo Gonzalez 3', b'$2,345', b'Grupo D')],
          dtype=[('col1', 'S80'), ('col2', 'S80'), ('col3', 'S80')])

2) Función que utilizando NumPy dada una matriz de dimension nxn pueda extraer las filas con valores desiguales y retorne una matrix sin esos elementos iguales 

- Input 

In [ ]:
matriz

array([[1, 2, 2, 1, 1, 1],
       [9, 9, 9, 9, 9, 9],
       [1, 2, 3, 4, 5, 6]])

- Output

In [ ]:
result

array([[1, 2, 2, 1, 1, 1],
       [1, 2, 3, 4, 5, 6]])

3) Función utilizando NumPy que dada una matriz de nx1 retorne una matriz de dimension (2*n+n -2)x1 donde en medio de cada uno de sus elementos añada dos ceros

- Input

In [ ]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
array.shape

(14,)

- Output

In [ ]:
result

array([ 1.,  0.,  0.,  2.,  0.,  0.,  3.,  0.,  0.,  4.,  0.,  0.,  5.,
        0.,  0.,  6.,  0.,  0.,  7.,  0.,  0.,  8.,  0.,  0.,  9.,  0.,
        0., 10.,  0.,  0., 11.,  0.,  0., 12.,  0.,  0., 13.,  0.,  0.,
       14.])

In [ ]:
result.shape

(40,)

In [ ]:
n=array.shape[0]

In [ ]:
2*n+n -2

40

In [ ]:
result.shape

(40,)

4) Escriba una función usando NumPy que reciba como parámetro:
    a)dimension_matriz=(12,12)
    b)dimension_sub_matriz=(4,4)
    
    -Generar matriz de números aleatorios entre 0-99 de la dimension especificada en el primer parámetro
    -Extraer todas las sub-matrices posibles de la dimension especificada en el segundo parámetro
    -En caso de que la dimension de la dimension_sub_matriz sea mayor a dimension_matriz debe de retornar un print mencionando que se debe ingresar una dimension menor
    -La función debe retornar una lista donde cada uno de sus elementos debe contener cada una de las submatrices

5) Función que tenga como parametros lo siguiente:
    - DataFrame de cualquier dimension, con valores numericos en todos sus registros  
    - N, un valor entero 
    Retorne una lista de longitud igual al número de columnas del DataFrame proporcionado, donde cada uno de sus elementos es un sub-DataFrame,Todos deben contener N registros, El primero de ellos debe tener los registros del DataFrame original con los N valores más bajos sobre la primer variable y asi sucesivamente
    

- Input

In [ ]:
df

variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
0           1           4           7           1           4          12
1           2           5           5         200         111           5
2           3        1206           8           3           6          32
3           4           9          12           4           9          12
4           7           5           1         767           5           1
5          11           0          11          11           0          11

In [ ]:
N=2

- Output 

In [ ]:
lista

[   variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
 0           1           4           7           1           4          12
 1           2           5           5         200         111           5,
    variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
 5          11           0          11          11           0          11
 0           1           4           7           1           4          12,
    variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
 4           7           5           1         767           5           1
 1           2           5           5         200         111           5,
    variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
 0           1           4           7           1           4          12
 2           3        1206           8           3           6          32,
    variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
 5          11       

In [ ]:
len(lista)

6

In [ ]:
lista[0]

variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
0           1           4           7           1           4          12
1           2           5           5         200         111           5

In [ ]:
lista[1]

variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
5          11           0          11          11           0          11
0           1           4           7           1           4          12

In [ ]:
lista[2]

variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
4           7           5           1         767           5           1
1           2           5           5         200         111           5

In [ ]:
lista[3]

variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
0           1           4           7           1           4          12
2           3        1206           8           3           6          32

In [ ]:
lista[4]

variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
5          11           0          11          11           0          11
0           1           4           7           1           4          12

In [ ]:
lista[5]

variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
4           7           5           1         767           5           1
1           2           5           5         200         111           5

In [57]:
import numpy as np
data = {'variable_1':[int(np.random.randint(0,50,1)) for x in range(0,5)],
        'variable_2':[int(np.random.randint(0,100,1)) for x in range(0,5)],
        'variable_3':[int(np.random.randint(0,150,1)) for x in range(0,5)],
        'variable_4':[int(np.random.randint(0,200,1)) for x in range(0,5)],
        'variable_5':[int(np.random.randint(0,250,1)) for x in range(0,5)],
        'variable_6':[int(np.random.randint(0,300,1)) for x in range(0,5)]}

import pandas as pd
data = pd.DataFrame(data)
data

variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
0          42          41          39         122          84         122
1           3           1         129         195         231         152
2          33          69           6         139         182         200
3           7          59          56           9         139          81
4           9          10          32         129          81         249

In [63]:
lista = []
N = 3
def small_2(df):
    for j in df.columns:
        lista.append(df.sort_values(by = j).iloc[:N,:])
    return lista

small_2(data)

[   variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
 1           3           1         129         195         231         152
 3           7          59          56           9         139          81
 4           9          10          32         129          81         249,
    variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
 1           3           1         129         195         231         152
 4           9          10          32         129          81         249
 0          42          41          39         122          84         122,
    variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
 2          33          69           6         139         182         200
 4           9          10          32         129          81         249
 0          42          41          39         122          84         122,
    variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
 3           7        

In [64]:
lista[3]

variable_1  variable_2  variable_3  variable_4  variable_5  variable_6
3           7          59          56           9         139          81
0          42          41          39         122          84         122
4           9          10          32         129          81         249

6)  Función que tenga como parámetro:

        -Dataframe con valores enteros o flotantes en todos sus registros
    
       Retorne un DataFrame de la misma dimension, donde revise columna por columna los registros, si el segundo registro es menor que el primer registro debe remplazar el valor por cero, si no pasa lo anterior debe conservar su valor original,si el tercer registro es menor que el segundo registro debe remplazarlo por cero, si no pasa lo anterior debe conservar su valor original y asi sucesivamente, Esto lo debe hacer columna por columna

- Input

In [ ]:
data

variable_1  variable_2
0           12           1
1           23          23
2           21          21
3           27          22
4           32          32
5           34          34
6           33          34
7           34          34
8            0           0
9           65          65
10          22          22
11          34         134
12          19          19
13          31          31
14          32        3442
15        2319          19

- Output

In [ ]:
data

variable_1  variable_2
0           12           1
1           23          23
2            0           0
3           27           0
4           32          32
5           34          34
6            0          34
7           34          34
8            0           0
9           65          65
10           0           0
11           0         134
12           0           0
13           0           0
14           0        3442
15        2319           0

In [34]:
import numpy as np
data = {'variable_1':[x for x in range(0,100)],
        'variable_2':[x for x in range(200,0,-2)],
        'variable_3':[int(np.random.randint(0,1000,1)) for x in range(0,100)]}

import pandas as pd
data = pd.DataFrame(data).sample(16).reset_index(drop = True)
data

variable_1  variable_2  variable_3
0           15         170         740
1           98           4         125
2           61          78         654
3           52          96         858
4           75          50         123
5           74          52         341
6           38         124          70
7           65          70         962
8           95          10         157
9           80          40         663
10           7         186         967
11          46         108         990
12          78          44         573
13           0         200         559
14          16         168         854
15           6         188         884

In [35]:
def menor(df):
    for j in df.columns: # Para cada columna
        aux = [] # Se va a crear una columna vacía
        for i in range(len(df)): # Y ahora, iterando cada renglón
            if i == 0:
                aux.append(df[j][0]) # Si es el primer renglón, dejar el elemento original
            else:
                if df[j][i] < df[j][i-1]: # Si el elemento analizado es menor vs el renglón anterior
                    aux.append(0) # Apilar un 0 en la lista auxiliar
                else:
                    aux.append(df[j][i]) # De otro modo, dejar el valor original
        df[j] = aux # Finalmente, sustituir la columna analizada
    return df

menor(data)

variable_1  variable_2  variable_3
0           15         170         740
1           98           0           0
2            0          78         654
3            0          96         858
4           75           0           0
5            0          52         341
6            0         124           0
7           65           0         962
8           95           0           0
9            0          40         663
10           0         186         967
11          46           0         990
12          78           0           0
13           0         200           0
14          16           0         854
15           0         188         884